# Cross compilation configuration
# https://github.com/cross-rs/cross

[build]
# Use pre-built Docker images for faster builds
pre-build = []

# Environment variables for all targets
[build.env]
passthrough = [
  "RUST_BACKTRACE",
  "CARGO_TERM_COLOR"
]

[target.aarch64-apple-darwin]

[target.aarch64-pc-windows-msvc]

[target.aarch64-unknown-linux-gnu]
# Use the latest cross image
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

[target.x86_64-apple-darwin]

[target.x86_64-pc-windows-msvc]

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest"
